static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 3000
    filter_chains: 
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: edge
          http_filters:
          - name: envoy.filters.http.router
          route_config: 
            virtual_hosts:
            - name: all_domains
              domains: ["*"]
              routes:
              - match:
                  prefix: "/server1"
                route: 
                  cluster: server1
              - match:
                  prefix: "/server2"
                route: 
                  cluster: server2
              - match:
                  prefix: "/server3"
                route: 
                  cluster: server3
              - match:
                  prefix: "/server4"
                route: 
                  cluster: server4
          
  clusters:
  - name: server1
    connect_timeout: 5s
    load_assignment:
      cluster_name: server1
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 10.0.1.1
                port_value: 8000
  - name: server2
    connect_timeout: 5s
    load_assignment:
      cluster_name: server2
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 10.0.2.1
                port_value: 8000
  - name: server3
    connect_timeout: 5s
    load_assignment:
      cluster_name: server3
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 10.0.3.1
                port_value: 8000
  - name: server4
    connect_timeout: 5s
    load_assignment:
      cluster_name: server4
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 10.0.4.1
                port_value: 8000