[package]
name = "l4fp"
version = "0.1.0"
edition = "2021"
description = "An IPC accelerator à la Cilium"

[lib]
name = "l4fp"
path = "src/proxy.rs"

[[bin]]
name = "l4fp"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.86"
as-bytes = "0.2.0"
clap = { version = "4.5.17", features = ["derive"] }
common = { path = "../common" }
libbpf-rs = { git = "https://github.com/libbpf/libbpf-rs.git", features = [
    "vendored",
], branch = "master" }
libbpf-sys = "1.4.5"
libc = "0.2.155"
tokio = { version = "1.41.0", features = ["full"] }
tracing = "0.1.43"
tracing-subscriber = "0.3.22"

[build-dependencies]
libbpf-cargo = "0.24"
