// SPDX-License-Identifier: (LGPL-2.1 OR BSD-2-Clause)
//
// THIS FILE IS AUTOGENERATED BY CARGO-LIBBPF-GEN!

pub use self::imp::*;

#[allow(dead_code)]
#[allow(non_snake_case)]
#[allow(non_camel_case_types)]
#[allow(clippy::absolute_paths)]
#[allow(clippy::transmute_ptr_to_ref)]
#[allow(clippy::upper_case_acronyms)]
#[warn(single_use_lifetimes)]
mod imp {
    #[allow(unused_imports)]
    use super::*;
    use libbpf_rs::libbpf_sys;
    use libbpf_rs::skel::OpenSkel;
    use libbpf_rs::skel::Skel;
    use libbpf_rs::skel::SkelBuilder;

    fn build_skel_config(
    ) -> libbpf_rs::Result<libbpf_rs::__internal_skel::ObjectSkeletonConfig<'static>> {
        let mut builder = libbpf_rs::__internal_skel::ObjectSkeletonConfigBuilder::new(DATA);
        builder
            .name("parser_bpf")
            .prog("bpf_prog_parser")
            .prog("bpf_prog_verdict");

        builder.build()
    }

    #[derive(Default)]
    pub struct ParserSkelBuilder {
        pub obj_builder: libbpf_rs::ObjectBuilder,
    }

    impl<'a> SkelBuilder<'a> for ParserSkelBuilder {
        type Output = OpenParserSkel<'a>;
        fn open(self) -> libbpf_rs::Result<OpenParserSkel<'a>> {
            let opts = *self.obj_builder.opts();
            self.open_opts(opts)
        }

        fn open_opts(
            self,
            open_opts: libbpf_sys::bpf_object_open_opts,
        ) -> libbpf_rs::Result<OpenParserSkel<'a>> {
            let mut skel_config = build_skel_config()?;

            let ret =
                unsafe { libbpf_sys::bpf_object__open_skeleton(skel_config.get(), &open_opts) };
            if ret != 0 {
                return Err(libbpf_rs::Error::from_raw_os_error(-ret));
            }

            let obj = unsafe { libbpf_rs::OpenObject::from_ptr(skel_config.object_ptr())? };

            #[allow(unused_mut)]
            let mut skel = OpenParserSkel {
                obj,
                // SAFETY: Our `struct_ops` type contains only pointers,
                //         which are allowed to be NULL.
                // TODO: Generate and use a `Default` representation
                //       instead, to cut down on unsafe code.
                struct_ops: unsafe { std::mem::zeroed() },
                skel_config,
            };

            Ok(skel)
        }

        fn object_builder(&self) -> &libbpf_rs::ObjectBuilder {
            &self.obj_builder
        }
        fn object_builder_mut(&mut self) -> &mut libbpf_rs::ObjectBuilder {
            &mut self.obj_builder
        }
    }

    pub struct OpenParserProgs<'a> {
        inner: &'a libbpf_rs::OpenObject,
    }

    impl OpenParserProgs<'_> {
        pub fn bpf_prog_parser(&self) -> &libbpf_rs::OpenProgram {
            self.inner.prog("bpf_prog_parser").unwrap()
        }

        pub fn bpf_prog_verdict(&self) -> &libbpf_rs::OpenProgram {
            self.inner.prog("bpf_prog_verdict").unwrap()
        }
    }

    pub struct OpenParserProgsMut<'a> {
        inner: &'a mut libbpf_rs::OpenObject,
    }

    impl OpenParserProgsMut<'_> {
        pub fn bpf_prog_parser(&mut self) -> &mut libbpf_rs::OpenProgram {
            self.inner.prog_mut("bpf_prog_parser").unwrap()
        }

        pub fn bpf_prog_verdict(&mut self) -> &mut libbpf_rs::OpenProgram {
            self.inner.prog_mut("bpf_prog_verdict").unwrap()
        }
    }

    pub mod parser_types {
        #[allow(unused_imports)]
        use super::*;

        #[derive(Debug, Clone)]
        #[repr(C)]
        pub struct struct_ops {}

        impl struct_ops {}
    }

    pub struct OpenParserSkel<'a> {
        pub obj: libbpf_rs::OpenObject,
        pub struct_ops: parser_types::struct_ops,
        skel_config: libbpf_rs::__internal_skel::ObjectSkeletonConfig<'a>,
    }

    impl<'a> OpenSkel for OpenParserSkel<'a> {
        type Output = ParserSkel<'a>;
        fn load(mut self) -> libbpf_rs::Result<ParserSkel<'a>> {
            let ret = unsafe { libbpf_sys::bpf_object__load_skeleton(self.skel_config.get()) };
            if ret != 0 {
                return Err(libbpf_rs::Error::from_raw_os_error(-ret));
            }

            let obj = unsafe { libbpf_rs::Object::from_ptr(self.obj.take_ptr())? };

            Ok(ParserSkel {
                obj,
                struct_ops: self.struct_ops,
                skel_config: self.skel_config,
                links: ParserLinks::default(),
            })
        }

        fn open_object(&self) -> &libbpf_rs::OpenObject {
            &self.obj
        }

        fn open_object_mut(&mut self) -> &mut libbpf_rs::OpenObject {
            &mut self.obj
        }
    }
    impl OpenParserSkel<'_> {
        pub fn progs_mut(&mut self) -> OpenParserProgsMut<'_> {
            OpenParserProgsMut {
                inner: &mut self.obj,
            }
        }

        pub fn progs(&self) -> OpenParserProgs<'_> {
            OpenParserProgs { inner: &self.obj }
        }
    }

    pub struct ParserProgs<'a> {
        inner: &'a libbpf_rs::Object,
    }

    impl ParserProgs<'_> {
        pub fn bpf_prog_parser(&self) -> &libbpf_rs::Program {
            self.inner.prog("bpf_prog_parser").unwrap()
        }

        pub fn bpf_prog_verdict(&self) -> &libbpf_rs::Program {
            self.inner.prog("bpf_prog_verdict").unwrap()
        }
    }

    pub struct ParserProgsMut<'a> {
        inner: &'a mut libbpf_rs::Object,
    }

    impl ParserProgsMut<'_> {
        pub fn bpf_prog_parser(&mut self) -> &mut libbpf_rs::Program {
            self.inner.prog_mut("bpf_prog_parser").unwrap()
        }

        pub fn bpf_prog_verdict(&mut self) -> &mut libbpf_rs::Program {
            self.inner.prog_mut("bpf_prog_verdict").unwrap()
        }
    }

    #[derive(Default)]
    pub struct ParserLinks {
        pub bpf_prog_parser: Option<libbpf_rs::Link>,
        pub bpf_prog_verdict: Option<libbpf_rs::Link>,
    }

    pub struct ParserSkel<'a> {
        pub obj: libbpf_rs::Object,
        struct_ops: parser_types::struct_ops,
        skel_config: libbpf_rs::__internal_skel::ObjectSkeletonConfig<'a>,
        pub links: ParserLinks,
    }

    unsafe impl Send for ParserSkel<'_> {}
    unsafe impl Sync for ParserSkel<'_> {}

    impl Skel for ParserSkel<'_> {
        fn object(&self) -> &libbpf_rs::Object {
            &self.obj
        }

        fn object_mut(&mut self) -> &mut libbpf_rs::Object {
            &mut self.obj
        }

        fn attach(&mut self) -> libbpf_rs::Result<()> {
            let ret = unsafe { libbpf_sys::bpf_object__attach_skeleton(self.skel_config.get()) };
            if ret != 0 {
                return Err(libbpf_rs::Error::from_raw_os_error(-ret));
            }

            self.links = ParserLinks {
                bpf_prog_parser: core::ptr::NonNull::new(self.skel_config.prog_link_ptr(0)?)
                    .map(|ptr| unsafe { libbpf_rs::Link::from_ptr(ptr) }),
                bpf_prog_verdict: core::ptr::NonNull::new(self.skel_config.prog_link_ptr(1)?)
                    .map(|ptr| unsafe { libbpf_rs::Link::from_ptr(ptr) }),
            };

            Ok(())
        }
    }
    impl ParserSkel<'_> {
        pub fn progs_mut(&mut self) -> ParserProgsMut<'_> {
            ParserProgsMut {
                inner: &mut self.obj,
            }
        }

        pub fn progs(&self) -> ParserProgs<'_> {
            ParserProgs { inner: &self.obj }
        }
    }

    const DATA: &[u8] = &[
        127, 69, 76, 70, 2, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 247, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 160, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 64, 0, 0, 0, 0,
        0, 64, 0, 8, 0, 1, 0, 0, 46, 115, 116, 114, 116, 97, 98, 0, 46, 115, 121, 109, 116, 97, 98,
        0, 115, 107, 95, 115, 107, 98, 47, 115, 116, 114, 101, 97, 109, 95, 112, 97, 114, 115, 101,
        114, 0, 115, 107, 95, 115, 107, 98, 47, 115, 116, 114, 101, 97, 109, 95, 118, 101, 114,
        100, 105, 99, 116, 0, 108, 105, 99, 101, 110, 115, 101, 0, 112, 97, 114, 115, 101, 114, 46,
        98, 112, 102, 46, 99, 0, 98, 112, 102, 95, 112, 114, 111, 103, 95, 112, 97, 114, 115, 101,
        114, 0, 98, 112, 102, 95, 112, 114, 111, 103, 95, 118, 101, 114, 100, 105, 99, 116, 0, 76,
        73, 67, 69, 78, 83, 69, 0, 46, 66, 84, 70, 0, 46, 66, 84, 70, 46, 101, 120, 116, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 68, 0, 0, 0, 4, 0, 241,
        255, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 3, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 81, 0, 0, 0, 18, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0,
        97, 0, 0, 0, 18, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0, 114, 0, 0, 0,
        17, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 97, 16, 0, 0, 0, 0, 0, 0, 149,
        0, 0, 0, 0, 0, 0, 0, 183, 0, 0, 0, 0, 0, 0, 0, 149, 0, 0, 0, 0, 0, 0, 0, 71, 80, 76, 0, 0,
        0, 0, 0, 159, 235, 1, 0, 24, 0, 0, 0, 0, 0, 0, 0, 252, 2, 0, 0, 252, 2, 0, 0, 87, 2, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 1, 0, 0, 0, 32, 0, 0, 4, 184, 0, 0, 0, 11, 0, 0, 0, 3,
        0, 0, 0, 0, 0, 0, 0, 15, 0, 0, 0, 3, 0, 0, 0, 32, 0, 0, 0, 24, 0, 0, 0, 3, 0, 0, 0, 64, 0,
        0, 0, 29, 0, 0, 0, 3, 0, 0, 0, 96, 0, 0, 0, 43, 0, 0, 0, 3, 0, 0, 0, 128, 0, 0, 0, 52, 0,
        0, 0, 3, 0, 0, 0, 160, 0, 0, 0, 65, 0, 0, 0, 3, 0, 0, 0, 192, 0, 0, 0, 74, 0, 0, 0, 3, 0,
        0, 0, 224, 0, 0, 0, 85, 0, 0, 0, 3, 0, 0, 0, 0, 1, 0, 0, 94, 0, 0, 0, 3, 0, 0, 0, 32, 1, 0,
        0, 110, 0, 0, 0, 3, 0, 0, 0, 64, 1, 0, 0, 118, 0, 0, 0, 3, 0, 0, 0, 96, 1, 0, 0, 127, 0, 0,
        0, 5, 0, 0, 0, 128, 1, 0, 0, 130, 0, 0, 0, 3, 0, 0, 0, 32, 2, 0, 0, 135, 0, 0, 0, 3, 0, 0,
        0, 64, 2, 0, 0, 146, 0, 0, 0, 3, 0, 0, 0, 96, 2, 0, 0, 151, 0, 0, 0, 3, 0, 0, 0, 128, 2, 0,
        0, 160, 0, 0, 0, 3, 0, 0, 0, 160, 2, 0, 0, 168, 0, 0, 0, 3, 0, 0, 0, 192, 2, 0, 0, 175, 0,
        0, 0, 3, 0, 0, 0, 224, 2, 0, 0, 186, 0, 0, 0, 3, 0, 0, 0, 0, 3, 0, 0, 196, 0, 0, 0, 7, 0,
        0, 0, 32, 3, 0, 0, 207, 0, 0, 0, 7, 0, 0, 0, 160, 3, 0, 0, 217, 0, 0, 0, 3, 0, 0, 0, 32, 4,
        0, 0, 229, 0, 0, 0, 3, 0, 0, 0, 64, 4, 0, 0, 240, 0, 0, 0, 3, 0, 0, 0, 96, 4, 0, 0, 0, 0,
        0, 0, 8, 0, 0, 0, 128, 4, 0, 0, 250, 0, 0, 0, 10, 0, 0, 0, 192, 4, 0, 0, 1, 1, 0, 0, 3, 0,
        0, 0, 0, 5, 0, 0, 10, 1, 0, 0, 3, 0, 0, 0, 32, 5, 0, 0, 0, 0, 0, 0, 12, 0, 0, 0, 64, 5, 0,
        0, 19, 1, 0, 0, 3, 0, 0, 0, 128, 5, 0, 0, 28, 1, 0, 0, 0, 0, 0, 8, 4, 0, 0, 0, 34, 1, 0, 0,
        0, 0, 0, 1, 4, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 3, 0, 0, 0, 6, 0,
        0, 0, 5, 0, 0, 0, 47, 1, 0, 0, 0, 0, 0, 1, 4, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3,
        0, 0, 0, 0, 3, 0, 0, 0, 6, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 5, 8, 0, 0, 0, 67, 1,
        0, 0, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 21, 0, 0, 0, 77, 1, 0, 0, 0, 0, 0, 8,
        11, 0, 0, 0, 83, 1, 0, 0, 0, 0, 0, 1, 8, 0, 0, 0, 64, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 5, 8,
        0, 0, 0, 102, 1, 0, 0, 13, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 22, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 13, 15, 0, 0, 0, 105, 1, 0, 0, 1, 0, 0, 0, 109, 1, 0, 0, 0, 0, 0, 1, 4, 0,
        0, 0, 32, 0, 0, 1, 113, 1, 0, 0, 1, 0, 0, 12, 14, 0, 0, 0, 129, 1, 0, 0, 1, 0, 0, 12, 14,
        0, 0, 0, 146, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 8, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0,
        0, 18, 0, 0, 0, 6, 0, 0, 0, 4, 0, 0, 0, 151, 1, 0, 0, 0, 0, 0, 14, 19, 0, 0, 0, 1, 0, 0, 0,
        159, 1, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 173, 1, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 36, 2, 0, 0, 1,
        0, 0, 15, 4, 0, 0, 0, 20, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 95, 95, 115, 107, 95, 98,
        117, 102, 102, 0, 108, 101, 110, 0, 112, 107, 116, 95, 116, 121, 112, 101, 0, 109, 97, 114,
        107, 0, 113, 117, 101, 117, 101, 95, 109, 97, 112, 112, 105, 110, 103, 0, 112, 114, 111,
        116, 111, 99, 111, 108, 0, 118, 108, 97, 110, 95, 112, 114, 101, 115, 101, 110, 116, 0,
        118, 108, 97, 110, 95, 116, 99, 105, 0, 118, 108, 97, 110, 95, 112, 114, 111, 116, 111, 0,
        112, 114, 105, 111, 114, 105, 116, 121, 0, 105, 110, 103, 114, 101, 115, 115, 95, 105, 102,
        105, 110, 100, 101, 120, 0, 105, 102, 105, 110, 100, 101, 120, 0, 116, 99, 95, 105, 110,
        100, 101, 120, 0, 99, 98, 0, 104, 97, 115, 104, 0, 116, 99, 95, 99, 108, 97, 115, 115, 105,
        100, 0, 100, 97, 116, 97, 0, 100, 97, 116, 97, 95, 101, 110, 100, 0, 110, 97, 112, 105, 95,
        105, 100, 0, 102, 97, 109, 105, 108, 121, 0, 114, 101, 109, 111, 116, 101, 95, 105, 112,
        52, 0, 108, 111, 99, 97, 108, 95, 105, 112, 52, 0, 114, 101, 109, 111, 116, 101, 95, 105,
        112, 54, 0, 108, 111, 99, 97, 108, 95, 105, 112, 54, 0, 114, 101, 109, 111, 116, 101, 95,
        112, 111, 114, 116, 0, 108, 111, 99, 97, 108, 95, 112, 111, 114, 116, 0, 100, 97, 116, 97,
        95, 109, 101, 116, 97, 0, 116, 115, 116, 97, 109, 112, 0, 119, 105, 114, 101, 95, 108, 101,
        110, 0, 103, 115, 111, 95, 115, 101, 103, 115, 0, 103, 115, 111, 95, 115, 105, 122, 101, 0,
        95, 95, 117, 51, 50, 0, 117, 110, 115, 105, 103, 110, 101, 100, 32, 105, 110, 116, 0, 95,
        95, 65, 82, 82, 65, 89, 95, 83, 73, 90, 69, 95, 84, 89, 80, 69, 95, 95, 0, 102, 108, 111,
        119, 95, 107, 101, 121, 115, 0, 95, 95, 117, 54, 52, 0, 117, 110, 115, 105, 103, 110, 101,
        100, 32, 108, 111, 110, 103, 32, 108, 111, 110, 103, 0, 115, 107, 0, 115, 107, 98, 0, 105,
        110, 116, 0, 98, 112, 102, 95, 112, 114, 111, 103, 95, 112, 97, 114, 115, 101, 114, 0, 98,
        112, 102, 95, 112, 114, 111, 103, 95, 118, 101, 114, 100, 105, 99, 116, 0, 99, 104, 97,
        114, 0, 76, 73, 67, 69, 78, 83, 69, 0, 98, 112, 102, 95, 102, 108, 111, 119, 95, 107, 101,
        121, 115, 0, 98, 112, 102, 95, 115, 111, 99, 107, 0, 47, 108, 111, 99, 97, 108, 47, 104,
        111, 109, 101, 47, 108, 97, 117, 114, 105, 110, 98, 47, 112, 114, 111, 106, 115, 47, 108,
        55, 45, 111, 102, 102, 108, 111, 97, 100, 47, 101, 120, 112, 115, 47, 99, 111, 109, 112,
        111, 115, 101, 47, 115, 114, 99, 47, 98, 112, 102, 47, 112, 97, 114, 115, 101, 114, 46, 98,
        112, 102, 46, 99, 0, 32, 32, 32, 32, 114, 101, 116, 117, 114, 110, 32, 115, 107, 98, 45,
        62, 108, 101, 110, 59, 0, 32, 32, 32, 32, 114, 101, 116, 117, 114, 110, 32, 48, 59, 0, 48,
        58, 48, 0, 108, 105, 99, 101, 110, 115, 101, 0, 115, 107, 95, 115, 107, 98, 47, 115, 116,
        114, 101, 97, 109, 95, 112, 97, 114, 115, 101, 114, 0, 115, 107, 95, 115, 107, 98, 47, 115,
        116, 114, 101, 97, 109, 95, 118, 101, 114, 100, 105, 99, 116, 0, 0, 0, 0, 0, 0, 159, 235,
        1, 0, 32, 0, 0, 0, 0, 0, 0, 0, 36, 0, 0, 0, 36, 0, 0, 0, 52, 0, 0, 0, 88, 0, 0, 0, 28, 0,
        0, 0, 8, 0, 0, 0, 44, 2, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 65, 2, 0, 0, 1, 0, 0,
        0, 0, 0, 0, 0, 17, 0, 0, 0, 16, 0, 0, 0, 44, 2, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 182, 1, 0, 0,
        253, 1, 0, 0, 5, 36, 0, 0, 65, 2, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 182, 1, 0, 0, 18, 2, 0, 0,
        5, 56, 0, 0, 16, 0, 0, 0, 44, 2, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 32, 2, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 3, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 64, 0, 0, 0, 0, 0, 0, 0, 136, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 200, 0, 0, 0, 0, 0, 0, 0, 168, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 24, 0, 0, 0, 0, 0, 0, 0, 17, 0, 0, 0, 1, 0, 0, 0, 6,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 112, 1, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 38, 0, 0, 0,
        1, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 128, 1, 0, 0, 0, 0, 0, 0, 16,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 60, 0, 0, 0, 1, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 144, 1, 0, 0,
        0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 122, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        152, 1, 0, 0, 0, 0, 0, 0, 107, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 127, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 8, 7, 0, 0, 0, 0, 0, 0, 148, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    ];
}
