socket: 172.17.0.1:9999
tls:
    socket: 0.0.0.0:9991
    cert: res/pem/cert.pem
    key: res/pem/key.pem
accelerate: 172.18.0.0/24
stats: true
hosts:
    - name: frontend
      http2: true
      instances:
          - 172.18.0.3:5000
    - name: profile
      http2: true
      instances:
          - 172.18.0.4:9999
    - name: search
      http2: true
      instances:
          - 172.18.0.5:9999
    - name: geo
      http2: true
      instances:
          - 172.18.0.6:9999
    - name: rate
      http2: true
      instances:
          - 172.18.0.7:9999
    - name: review
      http2: true
      instances:
          - 172.18.0.8:9999
    - name: attractions
      http2: true
      instances:
          - 172.18.0.10:9999
    - name: recommendation
      http2: true
      instances:
          - 172.18.0.11:9999
    - name: user
      http2: true
      instances:
          - 172.18.0.12:9999
    - name: reservation
      http2: true
      instances:
          - 172.18.0.13:9999
routes:
    - match:
          path: "/recommendations"
      dest: frontend
    - match:
          path: "/hotels"
      dest: frontend
    - match:
          path: "/search.Search/Nearby"
      filters:
          - type: mutate
            add:
                x-processed-by: beeline
      dest: search
    - match:
          path: "/reservation.Reservation/MakeReservation"
      filters:
          - type: mutate
            add:
                x-processed-by: beeline
      dest: reservation
    - match:
          path: "/reservation.Reservation/CheckAvailability"
      filters:
          - type: mutate
            add:
                x-processed-by: beeline
      dest: reservation
    - match:
          path: "/recommendation.Recommendation/GetRecommendations"
      filters:
          - type: mutate
            add:
                x-processed-by: beeline
      dest: recommendation
    - match:
          path: "/profile.Profile/GetProfiles"
      filters:
          - type: mutate
            add:
                x-processed-by: beeline
      dest: profile
    - match:
          path: "/user.User/CheckUser"
      filters:
          - type: mutate
            add:
                x-processed-by: beeline
      dest: user
    - match:
          path: "/reservation"
      dest: frontend
