socket: 172.17.0.1:9999
hosts:
    - name: unique-id-service
      instances:
          - 172.18.0.3:9999
    - name: movie-id-service
      instances:
          - 172.18.0.4:9999
    - name: text-service
      instances:
          - 172.18.0.7:9999
    - name: rating-service
      instances:
          - 172.18.0.8:9999
    - name: user-service
      instances:
          - 172.18.0.10:9999
    - name: compose-review-service
      instances:
          - 172.18.0.13:9999
    - name: review-storage-service
      instances:
          - 172.18.0.15:9999
    - name: user-review-service
      instances:
          - 172.18.0.18:9999
    - name: movie-review-service
      instances:
          - 172.18.0.21:9999
    - name: cast-info-service
      instances:
          - 172.18.0.25:9999
    - name: plot-service
      instances:
          - 172.18.0.28:9999
    - name: movie-info-service
      instances:
          - 172.18.0.31:9999
routes:
    - match:
          path: "/unique-id-service"
      filters:
          - type: jwt
            secret: "testtest12345678"
            issuer: beeline
      dest: unique-id-service
    - match:
          path: "/movie-id-service"
      filters:
          - type: jwt
            secret: "testtest12345678"
            issuer: beeline
      dest: movie-id-service
    - match:
          path: "/text-service"
      filters:
          - type: jwt
            secret: "testtest12345678"
            issuer: beeline
      dest: text-service
    - match:
          path: "/rating-service"
      filters:
          - type: jwt
            secret: "testtest12345678"
            issuer: beeline
      dest: rating-service
    - match:
          path: "/user-service"
      filters:
          - type: jwt
            secret: "testtest12345678"
            issuer: beeline
      dest: user-service
    - match:
          path: "/compose-review-service"
      filters:
          - type: jwt
            secret: "testtest12345678"
            issuer: beeline
      dest: compose-review-service
    - match:
          path: "/review-storage-service"
      filters:
          - type: jwt
            secret: "testtest12345678"
            issuer: beeline
      dest: review-storage-service
    - match:
          path: "/user-review-service"
      filters:
          - type: jwt
            secret: "testtest12345678"
            issuer: beeline
      dest: user-review-service
    - match:
          path: "/movie-review-service"
      filters:
          - type: jwt
            secret: "testtest12345678"
            issuer: beeline
      dest: movie-review-service
    - match:
          path: "/cast-info-service"
      filters:
          - type: jwt
            secret: "testtest12345678"
            issuer: beeline
      dest: cast-info-service
    - match:
          path: "/plot-service"
      filters:
          - type: jwt
            secret: "testtest12345678"
            issuer: beeline
      dest: plot-service
    - match:
          path: "/movie-info-service"
      filters:
          - type: jwt
            secret: "testtest12345678"
            issuer: beeline
      dest: movie-info-service
