socket: 172.17.0.1:9999
accelerate: 172.18.0.0/24
hosts:
    - name: unique-id-service
      instances:
          - 172.18.0.3:9999
    - name: movie-id-service
      instances:
          - 172.18.0.4:9999
    - name: text-service
      instances:
          - 172.18.0.7:9999
    - name: rating-service
      instances:
          - 172.18.0.8:9999
    - name: user-service
      instances:
          - 172.18.0.10:9999
    - name: compose-review-service
      instances:
          - 172.18.0.13:9999
    - name: review-storage-service
      instances:
          - 172.18.0.15:9999
    - name: user-review-service
      instances:
          - 172.18.0.18:9999
    - name: movie-review-service
      instances:
          - 172.18.0.21:9999
    - name: cast-info-service
      instances:
          - 172.18.0.25:9999
    - name: plot-service
      instances:
          - 172.18.0.28:9999
    - name: movie-info-service
      instances:
          - 172.18.0.31:9999
policies:
    - name: allow-unique-id-compose-review
      source_ip: 172.18.0.3
      method: POST
      path: "/compose-review-service"
      destination_port: 9999
      allow: true
    - name: allow-compose-review-review-storage
      source_ip: 172.18.0.13
      method: POST
      path: "/review-storage-service"
      destination_port: 9999
      allow: true
    - name: allow-compose-review-user-review
      source_ip: 172.18.0.13
      method: POST
      path: "/user-review-service"
      destination_port: 9999
      allow: true
    - name: allow-compose-review-movie-review
      source_ip: 172.18.0.13
      method: POST
      path: "/movie-review-service"
      destination_port: 9999
      allow: true
    - name: allow-movie-id-compose-review
      source_ip: 172.18.0.4
      method: POST
      path: "/compose-review-service"
      destination_port: 9999
      allow: true
    - name: allow-movie-id-rating
      source_ip: 172.18.0.4
      method: POST
      path: "/rating-service"
      destination_port: 9999
      allow: true
    - name: allow-movie-review-review-storage
      source_ip: 172.18.0.21
      method: POST
      path: "/review-storage-service"
      destination_port: 9999
      allow: true
    - name: allow-rating-compose-review
      source_ip: 172.18.0.8
      method: POST
      path: "/compose-review-service"
      destination_port: 9999
      allow: true
    - name: allow-text-compose-review
      source_ip: 172.18.0.7
      method: POST
      path: "/compose-review-service"
      destination_port: 9999
      allow: true
    - name: allow-user-review-review-storage
      source_ip: 172.18.0.18
      method: POST
      path: "/review-storage-service"
      destination_port: 9999
      allow: true
    - name: allow-user-compose-review
      source_ip: 172.18.0.10
      method: POST
      path: "/compose-review-service"
      destination_port: 9999
      allow: true
    - name: allow-frontend-user
      source_ip: 172.18.0.24
      method: POST
      path: "/user-service"
      destination_port: 9999
      allow: true
    - name: allow-frontend-movie-id
      source_ip: 172.18.0.24
      method: POST
      path: "/movie-id-service"
      destination_port: 9999
      allow: true
    - name: allow-frontend-compose-review
      source_ip: 172.18.0.24
      method: POST
      path: "/compose-review-service"
      destination_port: 9999
      allow: true
    - name: allow-frontend-unique-id
      source_ip: 172.18.0.24
      method: POST
      path: "/unique-id-service"
      destination_port: 9999
      allow: true
    - name: allow-frontend-text
      source_ip: 172.18.0.24
      method: POST
      path: "/text-service"
      destination_port: 9999
      allow: true
routes:
    - match:
          path: "/unique-id-service"
      filters:
          - type: mutate
            add:
                x-processed-by: beeline
      dest: unique-id-service
    - match:
          path: "/movie-id-service"
      filters:
          - type: mutate
            add:
                x-processed-by: beeline
      dest: movie-id-service
    - match:
          path: "/text-service"
      filters:
          - type: mutate
            add:
                x-processed-by: beeline
      dest: text-service
    - match:
          path: "/rating-service"
      filters:
          - type: mutate
            add:
                x-processed-by: beeline
      dest: rating-service
    - match:
          path: "/user-service"
      filters:
          - type: mutate
            add:
                x-processed-by: beeline
      dest: user-service
    - match:
          path: "/compose-review-service"
      filters:
          - type: mutate
            add:
                x-processed-by: beeline
      dest: compose-review-service
    - match:
          path: "/review-storage-service"
      filters:
          - type: mutate
            add:
                x-processed-by: beeline
      dest: review-storage-service
    - match:
          path: "/user-review-service"
      filters:
          - type: mutate
            add:
                x-processed-by: beeline
      dest: user-review-service
    - match:
          path: "/movie-review-service"
      filters:
          - type: mutate
            add:
                x-processed-by: beeline
      dest: movie-review-service
    - match:
          path: "/cast-info-service"
      filters:
          - type: mutate
            add:
                x-processed-by: beeline
      dest: cast-info-service
    - match:
          path: "/plot-service"
      filters:
          - type: mutate
            add:
                x-processed-by: beeline
      dest: plot-service
    - match:
          path: "/movie-info-service"
      filters:
          - type: mutate
            add:
                x-processed-by: beeline
      dest: movie-info-service
