socket: 172.17.0.1:9999
tls:
    socket: 0.0.0.0:9991
    cert: ../res/pem/cert.pem
    key: ../res/pem/key.pem
accelerate: 172.18.0.0/24
hosts:
    - name: nginx
      instances:
          - 172.18.0.37:8080
    - name: social-graph-service
      instances:
          - 172.18.0.2:9999
    - name: home-timeline-service
      instances:
          - 172.18.0.6:9999
    - name: compose-post-service
      instances:
          - 172.18.0.9:9999
    - name: post-storage-service
      instances:
          - 172.18.0.11:9999
    - name: user-timeline-service
      instances:
          - 172.18.0.15:9999
    - name: url-shorten-service
      instances:
          - 172.18.0.19:9999
    - name: user-service
      instances:
          - 172.18.0.23:9999
    - name: media-service
      instances:
          - 172.18.0.27:9999
    - name: text-service
      instances:
          - 172.18.0.31:9999
    - name: unique-id-service
      instances:
          - 172.18.0.33:9999
    - name: user-mention-service
      instances:
          - 172.18.0.35:9999
routes:
    - match:
          path: "/wrk2-api/post/compose"
      dest: nginx
    - match:
          path: "/social-graph-service"
      filters:
          - type: jwt
            secret: "testtest12345678"
            issuer: beeline
          - type: mutate
            add:
                x-processed-by: beeline
      dest: social-graph-service
    - match:
          path: "/home-timeline-service"
      filters:
          - type: jwt
            secret: "testtest12345678"
            issuer: beeline
          - type: mutate
            add:
                x-processed-by: beeline
      dest: home-timeline-service
    - match:
          path: "/compose-post-service"
      filters:
          - type: jwt
            secret: "testtest12345678"
            issuer: beeline
          - type: mutate
            add:
                x-processed-by: beeline
      dest: compose-post-service
    - match:
          path: "/post-storage-service"
      filters:
          - type: jwt
            secret: "testtest12345678"
            issuer: beeline
          - type: mutate
            add:
                x-processed-by: beeline
      dest: post-storage-service
    - match:
          path: "/user-timeline-service"
      filters:
          - type: jwt
            secret: "testtest12345678"
            issuer: beeline
          - type: mutate
            add:
                x-processed-by: beeline
      dest: user-timeline-service
    - match:
          path: "/url-shorten-service"
      filters:
          - type: jwt
            secret: "testtest12345678"
            issuer: beeline
          - type: mutate
            add:
                x-processed-by: beeline
      dest: url-shorten-service
    - match:
          path: "/user-service"
      filters:
          - type: jwt
            secret: "testtest12345678"
            issuer: beeline
          - type: mutate
            add:
                x-processed-by: beeline
      dest: user-service
    - match:
          path: "/media-service"
      filters:
          - type: jwt
            secret: "testtest12345678"
            issuer: beeline
          - type: mutate
            add:
                x-processed-by: beeline
      dest: media-service
    - match:
          path: "/text-service"
      filters:
          - type: jwt
            secret: "testtest12345678"
            issuer: beeline
          - type: mutate
            add:
                x-processed-by: beeline
      dest: text-service
    - match:
          path: "/unique-id-service"
      filters:
          - type: jwt
            secret: "testtest12345678"
            issuer: beeline
          - type: mutate
            add:
                x-processed-by: beeline
      dest: unique-id-service
    - match:
          path: "/user-mention-service"
      filters:
          - type: jwt
            secret: "testtest12345678"
            issuer: beeline
          - type: mutate
            add:
                x-processed-by: beeline
      dest: user-mention-service
