hosts:
    - name: social-graph-service
      instances:
          - 172.18.0.2:9999
    - name: home-timeline-service
      instances:
          - 172.18.0.6:9999
    - name: compose-post-service
      instances:
          - 172.18.0.9:9999
    - name: post-storage-service
      instances:
          - 172.18.0.11:9999
    - name: user-timeline-service
      instances:
          - 172.18.0.15:9999
    - name: url-shorten-service
      instances:
          - 172.18.0.19:9999
    - name: user-service
      instances:
          - 172.18.0.23:9999
    - name: media-service
      instances:
          - 172.18.0.27:9999
    - name: text-service
      instances:
          - 172.18.0.31:9999
    - name: unique-id-service
      instances:
          - 172.18.0.33:9999
    - name: user-mention-service
      instances:
          - 172.18.0.35:9999

parse:
    http:
        backend: str,
        content-length: u32
