name: hotel-reservation

networks:
    default:
        ipam:
            config:
                - subnet: 172.18.0.0/24

services:
    consul:
        image: hashicorp/consul:latest
        hostname: consul
        cgroup_parent: beeline.slice
        ports:
            - "8300:8300"
            - "8400:8400"
            - "8500:8500"
            - "8600:53/udp"
        command: ["agent", "-dev", "-log-level=info", "-client=0.0.0.0"]
        restart: always
        deploy:
            replicas: 1
            restart_policy:
                condition: any

    frontend:
        configs:
            - source: server_config
              target: /config.json
        cgroup_parent: beeline.slice
        hostname: frontend
        environment:
            - TLS
            - GC
            - JAEGER_SAMPLE_RATIO
            - LOG_LEVEL
        build:
            context: ../test/hotel_reservation
        image: deathstarbench/hotel-reservation:latest
        entrypoint: frontend
        ports:
            - "5000:5000"
        depends_on:
            - consul
        restart: always
        deploy:
            replicas: 1
            restart_policy:
                condition: any

    profile:
        configs:
            - source: server_config
              target: /config.json
        hostname: profile
        environment:
            - TLS
            - GC
            - JAEGER_SAMPLE_RATIO
            - LOG_LEVEL
        cgroup_parent: beeline.slice
        build:
            context: ../test/hotel_reservation
        image: deathstarbench/hotel-reservation:latest
        entrypoint: profile
        depends_on:
            - mongodb-profile
            - memcached-profile
            - consul
        restart: always
        deploy:
            replicas: 1
            restart_policy:
                condition: any

    search:
        configs:
            - source: server_config
              target: /config.json
        hostname: search
        environment:
            - TLS
            - GC
            - JAEGER_SAMPLE_RATIO
            - LOG_LEVEL
        cgroup_parent: beeline.slice
        build:
            context: ../test/hotel_reservation
        image: deathstarbench/hotel-reservation:latest
        entrypoint: search
        depends_on:
            - consul
        restart: always
        deploy:
            replicas: 1
            restart_policy:
                condition: any

    geo:
        configs:
            - source: server_config
              target: /config.json
        hostname: geo
        environment:
            - TLS
            - GC
            - JAEGER_SAMPLE_RATIO
            - LOG_LEVEL
        cgroup_parent: beeline.slice
        build:
            context: ../test/hotel_reservation
        image: deathstarbench/hotel-reservation:latest
        entrypoint: geo
        depends_on:
            - mongodb-geo
            - consul
        restart: always
        deploy:
            replicas: 1
            restart_policy:
                condition: any

    rate:
        configs:
            - source: server_config
              target: /config.json
        hostname: rate
        environment:
            - TLS
            - GC
            - JAEGER_SAMPLE_RATIO
            - LOG_LEVEL
        cgroup_parent: beeline.slice
        build:
            context: ../test/hotel_reservation
        image: deathstarbench/hotel-reservation:latest
        entrypoint: rate
        depends_on:
            - mongodb-rate
            - memcached-rate
            - consul
        restart: always
        deploy:
            replicas: 1
            restart_policy:
                condition: any

    review:
        configs:
            - source: server_config
              target: /workspace/config.json
        environment:
            - TLS
            - GC
            - JAEGER_SAMPLE_RATIO
            - MEMC_TIMEOUT
            - LOG_LEVEL
        hostname: review
        cgroup_parent: beeline.slice
        build:
            context: ../test/hotel_reservation
        image: hotel_reserv_review_single_node
        entrypoint: review
        container_name: "hotel_reserv_review"
        depends_on:
            - mongodb-review
            - memcached-review
            - consul
        restart: always

    attractions:
        environment:
            - TLS
            - GC
            - JAEGER_SAMPLE_RATIO
            - MEMC_TIMEOUT
            - LOG_LEVEL
        hostname: attractions
        cgroup_parent: beeline.slice
        build:
            context: ../test/hotel_reservation
        image: hotel_reserv_attractions_single_node
        entrypoint: attractions
        container_name: "hotel_reserv_attractions"
        depends_on:
            - mongodb-attractions
            - consul
        restart: always

    recommendation:
        configs:
            - source: server_config
              target: /config.json
        hostname: recommendation
        environment:
            - TLS
            - GC
            - JAEGER_SAMPLE_RATIO
            - LOG_LEVEL
        cgroup_parent: beeline.slice
        build:
            context: ../test/hotel_reservation
        image: deathstarbench/hotel-reservation:latest
        entrypoint: recommendation
        depends_on:
            - mongodb-recommendation
            - consul
        restart: always
        deploy:
            replicas: 1
            restart_policy:
                condition: any

    user:
        configs:
            - source: server_config
              target: /config.json
        hostname: user
        environment:
            - TLS
            - GC
            - JAEGER_SAMPLE_RATIO
            - LOG_LEVEL
        cgroup_parent: beeline.slice
        build:
            context: ../test/hotel_reservation
        image: deathstarbench/hotel-reservation:latest
        entrypoint: user
        depends_on:
            - mongodb-user
            - consul
        restart: always
        deploy:
            replicas: 1
            restart_policy:
                condition: any

    reservation:
        configs:
            - source: server_config
              target: /config.json
        hostname: reservation
        environment:
            - TLS
            - GC
            - JAEGER_SAMPLE_RATIO
            - LOG_LEVEL
        cgroup_parent: beeline.slice
        build:
            context: ../test/hotel_reservation
        image: deathstarbench/hotel-reservation:latest
        entrypoint: reservation
        depends_on:
            - mongodb-reservation
            - memcached-reserve
            - consul
        restart: always
        deploy:
            replicas: 1
            restart_policy:
                condition: any

    jaeger:
        image: jaegertracing/all-in-one:latest
        ports:
            - "14269"
            - "5778:5778"
            - "14268:14268"
            - "14267"
            - "16686:16686"
            - "5775:5775/udp"
            - "6831:6831/udp"
            - "6832:6832/udp"
        restart: always
        cgroup_parent: beeline.slice
        hostname: jaeger
        deploy:
            replicas: 1
            restart_policy:
                condition: any

    memcached-rate:
        image: memcached:latest
        hostname: rate-memcached
        cgroup_parent: beeline.slice
        environment:
            - MEMCACHED_CACHE_SIZE=128
            - MEMCACHED_THREADS=2
        logging:
            options:
                max-size: 50m
        restart: always
        deploy:
            replicas: 1
            restart_policy:
                condition: any

    memcached-review:
        image: memcached
        hostname: review-memcached
        container_name: "hotel_reserv_review_mmc"
        cgroup_parent: beeline.slice
        restart: always
        environment:
            - MEMCACHED_CACHE_SIZE=128
            - MEMCACHED_THREADS=2
        logging:
            options:
                max-size: 50m

    memcached-profile:
        image: memcached:latest
        hostname: profile-memcached
        cgroup_parent: beeline.slice
        environment:
            - MEMCACHED_CACHE_SIZE=128
            - MEMCACHED_THREADS=2
        logging:
            options:
                max-size: 50m
        restart: always
        deploy:
            replicas: 1
            restart_policy:
                condition: any

    memcached-reserve:
        image: memcached:latest
        hostname: reserve-memcached
        cgroup_parent: beeline.slice
        environment:
            - MEMCACHED_CACHE_SIZE=128
            - MEMCACHED_THREADS=2
        logging:
            options:
                max-size: 50m
        restart: always
        deploy:
            replicas: 1
            restart_policy:
                condition: any

    mongodb-geo:
        image: mongo:5.0
        hostname: geo-db
        cgroup_parent: beeline.slice
        volumes:
            - geo:/data/db
        restart: always
        deploy:
            replicas: 1
            restart_policy:
                condition: any

    mongodb-profile:
        image: mongo:5.0
        hostname: profile-db
        cgroup_parent: beeline.slice
        volumes:
            - profile:/data/db
        restart: always
        deploy:
            replicas: 1
            restart_policy:
                condition: any

    mongodb-rate:
        image: mongo:5.0
        hostname: rate-db
        cgroup_parent: beeline.slice
        volumes:
            - rate:/data/db
        restart: always
        deploy:
            replicas: 1
            restart_policy:
                condition: any

    mongodb-review:
        image: mongo:5.0
        hostname: review-db
        cgroup_parent: beeline.slice
        volumes:
            - review:/data/db
        restart: always
        deploy:
            replicas: 1
            restart_policy:
                condition: any

    mongodb-attractions:
        image: mongo:5.0
        cgroup_parent: beeline.slice
        hostname: attractions-db
        volumes:
            - attractions:/data/db
        restart: always
        deploy:
            replicas: 1
            restart_policy:
                condition: any

    mongodb-recommendation:
        image: mongo:5.0
        hostname: recommendation-db
        cgroup_parent: beeline.slice
        volumes:
            - recommendation:/data/db
        restart: always
        deploy:
            replicas: 1
            restart_policy:
                condition: any

    mongodb-reservation:
        image: mongo:5.0
        hostname: reservation-db
        cgroup_parent: beeline.slice
        volumes:
            - reservation:/data/db
        restart: always
        deploy:
            replicas: 1
            restart_policy:
                condition: any

    mongodb-user:
        image: mongo:5.0
        hostname: user-db
        cgroup_parent: beeline.slice
        volumes:
            - user:/data/db
        restart: always
        deploy:
            replicas: 1
            restart_policy:
                condition: any

volumes:
    geo:
    profile:
    rate:
    recommendation:
    reservation:
    user:
    review:
    attractions:

configs:
    server_config:
        file: ../test/hotel_reservation/config.json
