name: synthetic-service-mesh

networks:
    default:
        ipam:
            config:
                - subnet: 172.18.0.0/24

services:
    frontend:
        build:
            context: ..
            dockerfile: docker/Dockerfile.ssm
        ports:
            - 8080:8080
        entrypoint:
            [
                "ssm",
                "-a",
                "0.0.0.0:8080",
                "-s",
                "172.18.0.3:9999",
                "-c",
                "${SERVICES}",
            ]
        cgroup_parent: beeline.slice
        networks:
            default:
                ipv4_address: 172.18.0.2

    service:
        build:
            context: ..
            dockerfile: docker/Dockerfile.echo
        entrypoint: "echo -a 0.0.0.0:9999"
        cgroup_parent: beeline.slice
        deploy:
            replicas: ${SERVICES}
