name: social-network

networks:
    default:
        ipam:
            config:
                - subnet: 172.18.0.0/24
services:
    social-graph-service:
        build: ../social_network
        hostname: social-graph-service
        cpuset: 1-35
        extra_hosts:
            - "beeline:host-gateway"
        networks:
            default:
                ipv4_address: 172.18.0.2
        depends_on:
            jaeger-agent:
                condition: service_started
            social-graph-mongodb:
                condition: service_started
        restart: always
        entrypoint: SocialGraphService
        volumes:
            - ../social_network/config-beeline:/social-network-microservices/config

    social-graph-mongodb:
        image: mongo:4.4.6
        hostname: social-graph-mongodb
        cpuset: 1-35
        extra_hosts:
            - "beeline:host-gateway"
        networks:
            default:
                ipv4_address: 172.18.0.4
        restart: always

    social-graph-redis:
        image: redis
        command: redis-server --save "" --appendonly no
        hostname: social-graph-redis
        cpuset: 1-35
        extra_hosts:
            - "beeline:host-gateway"
        networks:
            default:
                ipv4_address: 172.18.0.5
        restart: always

    # ---

    home-timeline-service:
        build: ../social_network
        hostname: home-timeline-service
        cpuset: 1-35
        extra_hosts:
            - "beeline:host-gateway"
        networks:
            default:
                ipv4_address: 172.18.0.6
        depends_on:
            jaeger-agent:
                condition: service_started
        restart: always
        entrypoint: HomeTimelineService
        volumes:
            - ../social_network/config-beeline:/social-network-microservices/config

    home-timeline-redis:
        image: redis
        command: redis-server --save "" --appendonly no
        hostname: home-timeline-redis
        cpuset: 1-35
        extra_hosts:
            - "beeline:host-gateway"
        networks:
            default:
                ipv4_address: 172.18.0.8
        restart: always

    # ---

    compose-post-service:
        build: ../social_network
        hostname: compose-post-service
        cpuset: 1-35
        extra_hosts:
            - "beeline:host-gateway"
        networks:
            default:
                ipv4_address: 172.18.0.9
        restart: always
        depends_on:
            jaeger-agent:
                condition: service_started
        entrypoint: ComposePostService
        volumes:
            - ../social_network/config-beeline:/social-network-microservices/config

    # ---

    post-storage-service:
        build: ../social_network
        hostname: post-storage-service
        cpuset: 1-35
        extra_hosts:
            - "beeline:host-gateway"
        networks:
            default:
                ipv4_address: 172.18.0.11
        ports:
            - 10002:9999
        restart: always
        depends_on:
            jaeger-agent:
                condition: service_started
            post-storage-mongodb:
                condition: service_started
        entrypoint: PostStorageService
        volumes:
            - ../social_network/config-beeline:/social-network-microservices/config

    post-storage-memcached:
        image: memcached
        hostname: post-storage-memcached
        cpuset: 1-35
        extra_hosts:
            - "beeline:host-gateway"
        networks:
            default:
                ipv4_address: 172.18.0.13
        restart: always

    post-storage-mongodb:
        image: mongo:4.4.6
        hostname: post-storage-mongodb
        cpuset: 1-35
        extra_hosts:
            - "beeline:host-gateway"
        networks:
            default:
                ipv4_address: 172.18.0.14
        restart: always

    # ---

    user-timeline-service:
        build: ../social_network
        hostname: user-timeline-service
        cpuset: 1-35
        extra_hosts:
            - "beeline:host-gateway"
        networks:
            default:
                ipv4_address: 172.18.0.15
        restart: always
        depends_on:
            jaeger-agent:
                condition: service_started
            user-timeline-mongodb:
                condition: service_started
        entrypoint: UserTimelineService
        volumes:
            - ../social_network/config-beeline:/social-network-microservices/config

    user-timeline-redis:
        image: redis
        command: redis-server --save "" --appendonly no
        hostname: user-timeline-redis
        cpuset: 1-35
        extra_hosts:
            - "beeline:host-gateway"
        networks:
            default:
                ipv4_address: 172.18.0.17
        restart: always

    user-timeline-mongodb:
        image: mongo:4.4.6
        hostname: user-timeline-mongodb
        cpuset: 1-35
        extra_hosts:
            - "beeline:host-gateway"
        networks:
            default:
                ipv4_address: 172.18.0.18
        restart: always

    # ---

    url-shorten-service:
        build: ../social_network
        hostname: url-shorten-service
        cpuset: 1-35
        extra_hosts:
            - "beeline:host-gateway"
        networks:
            default:
                ipv4_address: 172.18.0.19
        restart: always
        entrypoint: UrlShortenService
        depends_on:
            jaeger-agent:
                condition: service_started
            url-shorten-mongodb:
                condition: service_started
        volumes:
            - ../social_network/config-beeline:/social-network-microservices/config

    url-shorten-memcached:
        image: memcached
        hostname: url-shorten-memcached
        cpuset: 1-35
        extra_hosts:
            - "beeline:host-gateway"
        networks:
            default:
                ipv4_address: 172.18.0.21
        restart: always

    url-shorten-mongodb:
        image: mongo:4.4.6
        hostname: url-shorten-mongodb
        cpuset: 1-35
        extra_hosts:
            - "beeline:host-gateway"
        networks:
            default:
                ipv4_address: 172.18.0.22
        restart: always

    # ---

    user-service:
        build: ../social_network
        hostname: user-service
        cpuset: 1-35
        extra_hosts:
            - "beeline:host-gateway"
        networks:
            default:
                ipv4_address: 172.18.0.23
        restart: always
        depends_on:
            jaeger-agent:
                condition: service_started
            user-mongodb:
                condition: service_started
        entrypoint: UserService
        volumes:
            - ../social_network/config-beeline:/social-network-microservices/config

    user-memcached:
        image: memcached
        hostname: user-memcached
        cpuset: 1-35
        extra_hosts:
            - "beeline:host-gateway"
        networks:
            default:
                ipv4_address: 172.18.0.25
        restart: always

    user-mongodb:
        image: mongo:4.4.6
        hostname: user-mongodb
        cpuset: 1-35
        extra_hosts:
            - "beeline:host-gateway"
        networks:
            default:
                ipv4_address: 172.18.0.26
        restart: always

    # ---

    media-service:
        build: ../social_network
        hostname: media-service
        cpuset: 1-35
        extra_hosts:
            - "beeline:host-gateway"
        networks:
            default:
                ipv4_address: 172.18.0.27
        depends_on:
            jaeger-agent:
                condition: service_started
            media-mongodb:
                condition: service_started
        restart: always
        entrypoint: MediaService
        volumes:
            - ../social_network/config-beeline:/social-network-microservices/config

    media-memcached:
        image: memcached
        hostname: media-memcached
        cpuset: 1-35
        extra_hosts:
            - "beeline:host-gateway"
        networks:
            default:
                ipv4_address: 172.18.0.29
        restart: always

    media-mongodb:
        image: mongo:4.4.6
        hostname: media-mongodb
        cpuset: 1-35
        extra_hosts:
            - "beeline:host-gateway"
        networks:
            default:
                ipv4_address: 172.18.0.30
        restart: always

    # ---

    text-service:
        build: ../social_network
        hostname: text-service
        cpuset: 1-35
        extra_hosts:
            - "beeline:host-gateway"
        networks:
            default:
                ipv4_address: 172.18.0.31
        restart: always
        depends_on:
            jaeger-agent:
                condition: service_started
        entrypoint: TextService
        volumes:
            - ../social_network/config-beeline:/social-network-microservices/config

    # ---

    unique-id-service:
        build: ../social_network
        hostname: unique-id-service
        cpuset: 1-35
        extra_hosts:
            - "beeline:host-gateway"
        networks:
            default:
                ipv4_address: 172.18.0.33
        restart: always
        depends_on:
            jaeger-agent:
                condition: service_started
        entrypoint: UniqueIdService
        volumes:
            - ../social_network/config-beeline:/social-network-microservices/config

    # ---

    user-mention-service:
        build: ../social_network
        hostname: user-mention-service
        cpuset: 1-35
        extra_hosts:
            - "beeline:host-gateway"
        networks:
            default:
                ipv4_address: 172.18.0.35
        depends_on:
            jaeger-agent:
                condition: service_started
        restart: always
        entrypoint: UserMentionService
        volumes:
            - ../social_network/config-beeline:/social-network-microservices/config

    # ---

    nginx-thrift:
        image: yg397/openresty-thrift:xenial
        hostname: nginx-thrift
        cpuset: 1-35
        extra_hosts:
            - "beeline:host-gateway"
        networks:
            default:
                ipv4_address: 172.18.0.37
        ports:
            - 8080:8080
        depends_on:
            jaeger-agent:
                condition: service_started
        restart: always
        volumes:
            - ../social_network/nginx-web-server/lua-scripts:/usr/local/openresty/nginx/lua-scripts
            - ../social_network/nginx-web-server/pages:/usr/local/openresty/nginx/pages
            - ../social_network/nginx-web-server/conf/nginx-beeline.conf:/usr/local/openresty/nginx/conf/nginx.conf
            - ../social_network/nginx-web-server/jaeger-config.json:/usr/local/openresty/nginx/jaeger-config.json
            - ../social_network/gen-lua:/gen-lua
            - ../social_network/docker/openresty-thrift/lua-thrift:/usr/local/openresty/lualib/thrift

    media-frontend:
        image: yg397/media-frontend:xenial
        hostname: media-frontend
        cpuset: 1-35
        extra_hosts:
            - "beeline:host-gateway"
        networks:
            default:
                ipv4_address: 172.18.0.38
        ports:
            - 8081:8080
        restart: always
        depends_on:
            jaeger-agent:
                condition: service_started
        volumes:
            - ../social_network/media-frontend/lua-scripts:/usr/local/openresty/nginx/lua-scripts
            - ../social_network/media-frontend/conf/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf

    jaeger-agent:
        image: jaegertracing/all-in-one:1.62.0
        networks:
            default:
                ipv4_address: 172.18.0.39
        ports:
            #      - 5775:5775/udp
            #      - 6831:6831/udp
            #      - 6832:6832/udp
            #      - 5778:5778
            - 16686:16686
            #      - 14268:14268
            #      - 9411:9411
        restart: always
        environment:
            - COLLECTOR_ZIPKIN_HTTP_PORT=9411

    sidecar:
        image: envoyproxy/envoy:v1.31-latest
        hostname: sidecar
        cpuset: 1-35
        extra_hosts:
            - "beeline:host-gateway"
        networks:
            default:
                ipv4_address: 172.18.0.40
        restart: always
        volumes:
            - ../social_network/config-beeline/sidecar.yaml:/etc/envoy/envoy.yaml
