name: synthetic-service-mesh

networks:
    default:
        ipam:
            config:
                - subnet: 172.18.0.0/24

services:
    frontend:
        build:
            context: ..
            dockerfile: docker/Dockerfile.frontend
        ports:
            - 8080:8080
        extra_hosts:
            - "beeline:host-gateway"
        entrypoint:
            [
                "frontend",
                "-a",
                "0.0.0.0:8080",
                "-p",
                "beeline:9999",
                "-s",
                "service-",
                "-n",
                "${SERVICES:-${REPLICAS}}",
                "${FRONTEND_ARGS}",
            ]
        cgroup_parent: beeline.slice
        networks:
            default:
                ipv4_address: 172.18.0.2

    service:
        build:
            context: ..
            dockerfile: docker/Dockerfile.echo
        entrypoint: "echo -a 0.0.0.0:9999"
        cgroup_parent: beeline.slice
        deploy:
            replicas: ${REPLICAS}
        depends_on:
            - frontend

    # this container is setup only to simplify network
    # an envoy proxy will be loaded into the network namespace of this container
    sidecar:
        build:
            context: ..
            dockerfile: docker/Dockerfile.echo
        entrypoint: "echo -a 0.0.0.0:8888"
        cgroup_parent: beeline.slice
        hostname: sidecar
        networks:
            default:
                ipv4_address: 172.18.0.254
