// SPDX-License-Identifier: (LGPL-2.1 OR BSD-2-Clause)
//
// THIS FILE IS AUTOGENERATED BY CARGO-LIBBPF-GEN!

pub use self::imp::*;

#[allow(dead_code)]
#[allow(non_snake_case)]
#[allow(non_camel_case_types)]
#[allow(clippy::absolute_paths)]
#[allow(clippy::transmute_ptr_to_ref)]
#[allow(clippy::upper_case_acronyms)]
#[warn(single_use_lifetimes)]
mod imp {
    #[allow(unused_imports)]
    use super::*;
    use libbpf_rs::libbpf_sys;
    use libbpf_rs::skel::OpenSkel;
    use libbpf_rs::skel::Skel;
    use libbpf_rs::skel::SkelBuilder;

    fn build_skel_config(
    ) -> libbpf_rs::Result<libbpf_rs::__internal_skel::ObjectSkeletonConfig<'static>> {
        let mut builder = libbpf_rs::__internal_skel::ObjectSkeletonConfigBuilder::new(DATA);
        builder
            .name("uprobe_bpf")
            .map("uprobe_b.rodata", false)
            .prog("uprobe_read_req");

        builder.build()
    }

    #[derive(Default)]
    pub struct UprobeSkelBuilder {
        pub obj_builder: libbpf_rs::ObjectBuilder,
    }

    impl<'a> SkelBuilder<'a> for UprobeSkelBuilder {
        type Output = OpenUprobeSkel<'a>;
        fn open(self) -> libbpf_rs::Result<OpenUprobeSkel<'a>> {
            let opts = *self.obj_builder.opts();
            self.open_opts(opts)
        }

        fn open_opts(
            self,
            open_opts: libbpf_sys::bpf_object_open_opts,
        ) -> libbpf_rs::Result<OpenUprobeSkel<'a>> {
            let mut skel_config = build_skel_config()?;

            let ret =
                unsafe { libbpf_sys::bpf_object__open_skeleton(skel_config.get(), &open_opts) };
            if ret != 0 {
                return Err(libbpf_rs::Error::from_raw_os_error(-ret));
            }

            let obj = unsafe { libbpf_rs::OpenObject::from_ptr(skel_config.object_ptr())? };

            #[allow(unused_mut)]
            let mut skel = OpenUprobeSkel {
                obj,
                // SAFETY: Our `struct_ops` type contains only pointers,
                //         which are allowed to be NULL.
                // TODO: Generate and use a `Default` representation
                //       instead, to cut down on unsafe code.
                struct_ops: unsafe { std::mem::zeroed() },
                skel_config,
            };

            Ok(skel)
        }

        fn object_builder(&self) -> &libbpf_rs::ObjectBuilder {
            &self.obj_builder
        }
        fn object_builder_mut(&mut self) -> &mut libbpf_rs::ObjectBuilder {
            &mut self.obj_builder
        }
    }

    pub struct OpenUprobeMapsMut<'a> {
        inner: &'a mut libbpf_rs::OpenObject,
    }

    impl OpenUprobeMapsMut<'_> {
        pub fn rodata(&mut self) -> &mut libbpf_rs::OpenMap {
            self.inner.map_mut("uprobe_b.rodata").unwrap()
        }
    }

    pub struct OpenUprobeMaps<'a> {
        inner: &'a libbpf_rs::OpenObject,
    }

    impl OpenUprobeMaps<'_> {
        pub fn rodata(&self) -> &libbpf_rs::OpenMap {
            self.inner.map("uprobe_b.rodata").unwrap()
        }
    }

    pub struct OpenUprobeProgs<'a> {
        inner: &'a libbpf_rs::OpenObject,
    }

    impl OpenUprobeProgs<'_> {
        pub fn uprobe_read_req(&self) -> &libbpf_rs::OpenProgram {
            self.inner.prog("uprobe_read_req").unwrap()
        }
    }

    pub struct OpenUprobeProgsMut<'a> {
        inner: &'a mut libbpf_rs::OpenObject,
    }

    impl OpenUprobeProgsMut<'_> {
        pub fn uprobe_read_req(&mut self) -> &mut libbpf_rs::OpenProgram {
            self.inner.prog_mut("uprobe_read_req").unwrap()
        }
    }

    pub mod uprobe_types {
        #[allow(unused_imports)]
        use super::*;
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct rodata {}

        #[derive(Debug, Clone)]
        #[repr(C)]
        pub struct struct_ops {}

        impl struct_ops {}
    }

    pub struct OpenUprobeSkel<'a> {
        pub obj: libbpf_rs::OpenObject,
        pub struct_ops: uprobe_types::struct_ops,
        skel_config: libbpf_rs::__internal_skel::ObjectSkeletonConfig<'a>,
    }

    impl<'a> OpenSkel for OpenUprobeSkel<'a> {
        type Output = UprobeSkel<'a>;
        fn load(mut self) -> libbpf_rs::Result<UprobeSkel<'a>> {
            let ret = unsafe { libbpf_sys::bpf_object__load_skeleton(self.skel_config.get()) };
            if ret != 0 {
                return Err(libbpf_rs::Error::from_raw_os_error(-ret));
            }

            let obj = unsafe { libbpf_rs::Object::from_ptr(self.obj.take_ptr())? };

            Ok(UprobeSkel {
                obj,
                struct_ops: self.struct_ops,
                skel_config: self.skel_config,
                links: UprobeLinks::default(),
            })
        }

        fn open_object(&self) -> &libbpf_rs::OpenObject {
            &self.obj
        }

        fn open_object_mut(&mut self) -> &mut libbpf_rs::OpenObject {
            &mut self.obj
        }
    }
    impl OpenUprobeSkel<'_> {
        pub fn progs_mut(&mut self) -> OpenUprobeProgsMut<'_> {
            OpenUprobeProgsMut {
                inner: &mut self.obj,
            }
        }

        pub fn progs(&self) -> OpenUprobeProgs<'_> {
            OpenUprobeProgs { inner: &self.obj }
        }

        pub fn maps_mut(&mut self) -> OpenUprobeMapsMut<'_> {
            OpenUprobeMapsMut {
                inner: &mut self.obj,
            }
        }

        pub fn maps(&self) -> OpenUprobeMaps<'_> {
            OpenUprobeMaps { inner: &self.obj }
        }
    }

    pub struct UprobeMapsMut<'a> {
        inner: &'a mut libbpf_rs::Object,
    }

    impl UprobeMapsMut<'_> {
        pub fn rodata(&mut self) -> &mut libbpf_rs::Map {
            self.inner.map_mut("uprobe_b.rodata").unwrap()
        }
    }

    pub struct UprobeMaps<'a> {
        inner: &'a libbpf_rs::Object,
    }

    impl UprobeMaps<'_> {
        pub fn rodata(&self) -> &libbpf_rs::Map {
            self.inner.map("uprobe_b.rodata").unwrap()
        }
    }

    pub struct UprobeProgs<'a> {
        inner: &'a libbpf_rs::Object,
    }

    impl UprobeProgs<'_> {
        pub fn uprobe_read_req(&self) -> &libbpf_rs::Program {
            self.inner.prog("uprobe_read_req").unwrap()
        }
    }

    pub struct UprobeProgsMut<'a> {
        inner: &'a mut libbpf_rs::Object,
    }

    impl UprobeProgsMut<'_> {
        pub fn uprobe_read_req(&mut self) -> &mut libbpf_rs::Program {
            self.inner.prog_mut("uprobe_read_req").unwrap()
        }
    }

    #[derive(Default)]
    pub struct UprobeLinks {
        pub uprobe_read_req: Option<libbpf_rs::Link>,
    }

    pub struct UprobeSkel<'a> {
        pub obj: libbpf_rs::Object,
        struct_ops: uprobe_types::struct_ops,
        skel_config: libbpf_rs::__internal_skel::ObjectSkeletonConfig<'a>,
        pub links: UprobeLinks,
    }

    unsafe impl Send for UprobeSkel<'_> {}
    unsafe impl Sync for UprobeSkel<'_> {}

    impl Skel for UprobeSkel<'_> {
        fn object(&self) -> &libbpf_rs::Object {
            &self.obj
        }

        fn object_mut(&mut self) -> &mut libbpf_rs::Object {
            &mut self.obj
        }

        fn attach(&mut self) -> libbpf_rs::Result<()> {
            let ret = unsafe { libbpf_sys::bpf_object__attach_skeleton(self.skel_config.get()) };
            if ret != 0 {
                return Err(libbpf_rs::Error::from_raw_os_error(-ret));
            }

            self.links = UprobeLinks {
                uprobe_read_req: core::ptr::NonNull::new(self.skel_config.prog_link_ptr(0)?)
                    .map(|ptr| unsafe { libbpf_rs::Link::from_ptr(ptr) }),
            };

            Ok(())
        }
    }
    impl UprobeSkel<'_> {
        pub fn progs_mut(&mut self) -> UprobeProgsMut<'_> {
            UprobeProgsMut {
                inner: &mut self.obj,
            }
        }

        pub fn progs(&self) -> UprobeProgs<'_> {
            UprobeProgs { inner: &self.obj }
        }

        pub fn maps_mut(&mut self) -> UprobeMapsMut<'_> {
            UprobeMapsMut {
                inner: &mut self.obj,
            }
        }

        pub fn maps(&self) -> UprobeMaps<'_> {
            UprobeMaps { inner: &self.obj }
        }

        pub fn struct_ops_raw(&self) -> *const uprobe_types::struct_ops {
            &self.struct_ops
        }

        pub fn struct_ops(&self) -> &uprobe_types::struct_ops {
            &self.struct_ops
        }
    }

    const DATA: &[u8] = &[
        127, 69, 76, 70, 2, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 247, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 160, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 64, 0, 0, 0, 0,
        0, 64, 0, 9, 0, 1, 0, 0, 46, 115, 116, 114, 116, 97, 98, 0, 46, 115, 121, 109, 116, 97, 98,
        0, 117, 112, 114, 111, 98, 101, 47, 114, 101, 97, 100, 95, 114, 101, 113, 0, 108, 105, 99,
        101, 110, 115, 101, 0, 46, 114, 111, 100, 97, 116, 97, 0, 117, 112, 114, 111, 98, 101, 46,
        98, 112, 102, 46, 99, 0, 95, 95, 95, 95, 117, 112, 114, 111, 98, 101, 95, 114, 101, 97,
        100, 95, 114, 101, 113, 46, 95, 95, 95, 95, 102, 109, 116, 0, 117, 112, 114, 111, 98, 101,
        95, 114, 101, 97, 100, 95, 114, 101, 113, 0, 76, 73, 67, 69, 78, 83, 69, 0, 46, 114, 101,
        108, 117, 112, 114, 111, 98, 101, 47, 114, 101, 97, 100, 95, 114, 101, 113, 0, 46, 66, 84,
        70, 0, 46, 66, 84, 70, 46, 101, 120, 116, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 49, 0, 0, 0, 4, 0, 241, 255, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 62, 0, 0, 0, 1, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 37, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        3, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 90, 0, 0, 0, 18, 0, 3, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 96, 0, 0, 0, 0, 0, 0, 0, 106, 0, 0, 0, 17, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 4, 0, 0, 0, 0, 0, 0, 0, 133, 0, 0, 0, 14, 0, 0, 0, 191, 4, 0, 0, 0, 0, 0, 0, 119, 4, 0,
        0, 32, 0, 0, 0, 191, 165, 0, 0, 0, 0, 0, 0, 7, 5, 0, 0, 240, 255, 255, 255, 24, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 183, 2, 0, 0, 37, 0, 0, 0, 191, 3, 0, 0, 0, 0, 0, 0, 133,
        0, 0, 0, 6, 0, 0, 0, 183, 0, 0, 0, 0, 0, 0, 0, 149, 0, 0, 0, 0, 0, 0, 0, 71, 80, 76, 0,
        117, 112, 114, 111, 98, 101, 32, 124, 32, 112, 105, 100, 58, 32, 37, 100, 44, 32, 116, 103,
        105, 100, 58, 32, 37, 100, 44, 32, 99, 111, 109, 109, 58, 32, 37, 115, 0, 0, 0, 0, 0, 0, 0,
        0, 40, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 4, 0, 0, 0, 159, 235, 1, 0, 24, 0, 0, 0, 0, 0, 0,
        0, 0, 2, 0, 0, 0, 2, 0, 0, 214, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 1, 0, 0, 0,
        21, 0, 0, 4, 168, 0, 0, 0, 9, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 13, 0, 0, 0, 3, 0, 0, 0, 64,
        0, 0, 0, 17, 0, 0, 0, 3, 0, 0, 0, 128, 0, 0, 0, 21, 0, 0, 0, 3, 0, 0, 0, 192, 0, 0, 0, 25,
        0, 0, 0, 3, 0, 0, 0, 0, 1, 0, 0, 28, 0, 0, 0, 3, 0, 0, 0, 64, 1, 0, 0, 31, 0, 0, 0, 3, 0,
        0, 0, 128, 1, 0, 0, 35, 0, 0, 0, 3, 0, 0, 0, 192, 1, 0, 0, 39, 0, 0, 0, 3, 0, 0, 0, 0, 2,
        0, 0, 42, 0, 0, 0, 3, 0, 0, 0, 64, 2, 0, 0, 45, 0, 0, 0, 3, 0, 0, 0, 128, 2, 0, 0, 48, 0,
        0, 0, 3, 0, 0, 0, 192, 2, 0, 0, 51, 0, 0, 0, 3, 0, 0, 0, 0, 3, 0, 0, 54, 0, 0, 0, 3, 0, 0,
        0, 64, 3, 0, 0, 57, 0, 0, 0, 3, 0, 0, 0, 128, 3, 0, 0, 60, 0, 0, 0, 3, 0, 0, 0, 192, 3, 0,
        0, 68, 0, 0, 0, 3, 0, 0, 0, 0, 4, 0, 0, 71, 0, 0, 0, 3, 0, 0, 0, 64, 4, 0, 0, 74, 0, 0, 0,
        3, 0, 0, 0, 128, 4, 0, 0, 80, 0, 0, 0, 3, 0, 0, 0, 192, 4, 0, 0, 83, 0, 0, 0, 3, 0, 0, 0,
        0, 5, 0, 0, 86, 0, 0, 0, 0, 0, 0, 1, 8, 0, 0, 0, 64, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 13, 5,
        0, 0, 0, 100, 0, 0, 0, 1, 0, 0, 0, 104, 0, 0, 0, 0, 0, 0, 1, 4, 0, 0, 0, 32, 0, 0, 1, 108,
        0, 0, 0, 1, 0, 0, 12, 4, 0, 0, 0, 124, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 8, 0, 0, 1, 0, 0,
        0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 7, 0, 0, 0, 9, 0, 0, 0, 4, 0, 0, 0, 129, 0, 0, 0, 0, 0, 0, 1,
        4, 0, 0, 0, 32, 0, 0, 0, 149, 0, 0, 0, 0, 0, 0, 14, 8, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 10, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 11, 0, 0, 0, 9, 0, 0, 0, 37, 0,
        0, 0, 157, 0, 0, 0, 0, 0, 0, 14, 12, 0, 0, 0, 0, 0, 0, 0, 182, 1, 0, 0, 1, 0, 0, 15, 4, 0,
        0, 0, 10, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 190, 1, 0, 0, 1, 0, 0, 15, 37, 0, 0, 0, 13, 0,
        0, 0, 0, 0, 0, 0, 37, 0, 0, 0, 0, 112, 116, 95, 114, 101, 103, 115, 0, 114, 49, 53, 0, 114,
        49, 52, 0, 114, 49, 51, 0, 114, 49, 50, 0, 98, 112, 0, 98, 120, 0, 114, 49, 49, 0, 114, 49,
        48, 0, 114, 57, 0, 114, 56, 0, 97, 120, 0, 99, 120, 0, 100, 120, 0, 115, 105, 0, 100, 105,
        0, 111, 114, 105, 103, 95, 97, 120, 0, 105, 112, 0, 99, 115, 0, 102, 108, 97, 103, 115, 0,
        115, 112, 0, 115, 115, 0, 117, 110, 115, 105, 103, 110, 101, 100, 32, 108, 111, 110, 103,
        0, 99, 116, 120, 0, 105, 110, 116, 0, 117, 112, 114, 111, 98, 101, 95, 114, 101, 97, 100,
        95, 114, 101, 113, 0, 99, 104, 97, 114, 0, 95, 95, 65, 82, 82, 65, 89, 95, 83, 73, 90, 69,
        95, 84, 89, 80, 69, 95, 95, 0, 76, 73, 67, 69, 78, 83, 69, 0, 95, 95, 95, 95, 117, 112,
        114, 111, 98, 101, 95, 114, 101, 97, 100, 95, 114, 101, 113, 46, 95, 95, 95, 95, 102, 109,
        116, 0, 47, 108, 111, 99, 97, 108, 47, 104, 111, 109, 101, 47, 108, 97, 117, 114, 105, 110,
        98, 47, 112, 114, 111, 106, 115, 47, 108, 55, 45, 111, 102, 102, 108, 111, 97, 100, 47,
        101, 120, 112, 115, 47, 114, 112, 99, 115, 110, 111, 111, 112, 47, 115, 114, 99, 47, 98,
        112, 102, 47, 117, 112, 114, 111, 98, 101, 46, 98, 112, 102, 46, 99, 0, 32, 32, 32, 32, 95,
        95, 117, 54, 52, 32, 116, 97, 115, 107, 32, 61, 32, 98, 112, 102, 95, 103, 101, 116, 95,
        99, 117, 114, 114, 101, 110, 116, 95, 112, 105, 100, 95, 116, 103, 105, 100, 40, 41, 59, 0,
        32, 32, 32, 32, 95, 95, 117, 51, 50, 32, 116, 103, 105, 100, 32, 61, 32, 116, 97, 115, 107,
        32, 62, 62, 32, 51, 50, 59, 0, 32, 32, 32, 32, 98, 112, 102, 95, 112, 114, 105, 110, 116,
        107, 40, 34, 117, 112, 114, 111, 98, 101, 32, 124, 32, 112, 105, 100, 58, 32, 37, 100, 44,
        32, 116, 103, 105, 100, 58, 32, 37, 100, 44, 32, 99, 111, 109, 109, 58, 32, 37, 115, 34,
        44, 32, 112, 105, 100, 44, 32, 116, 103, 105, 100, 44, 32, 99, 111, 109, 109, 41, 59, 0,
        105, 110, 116, 32, 66, 80, 70, 95, 85, 80, 82, 79, 66, 69, 40, 117, 112, 114, 111, 98, 101,
        95, 114, 101, 97, 100, 95, 114, 101, 113, 41, 32, 123, 0, 108, 105, 99, 101, 110, 115, 101,
        0, 46, 114, 111, 100, 97, 116, 97, 0, 117, 112, 114, 111, 98, 101, 47, 114, 101, 97, 100,
        95, 114, 101, 113, 0, 0, 0, 159, 235, 1, 0, 32, 0, 0, 0, 0, 0, 0, 0, 20, 0, 0, 0, 20, 0, 0,
        0, 92, 0, 0, 0, 112, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 198, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        6, 0, 0, 0, 16, 0, 0, 0, 198, 1, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 185, 0, 0, 0, 1, 1, 0, 0,
        18, 48, 0, 0, 8, 0, 0, 0, 185, 0, 0, 0, 46, 1, 0, 0, 23, 52, 0, 0, 32, 0, 0, 0, 185, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 40, 0, 0, 0, 185, 0, 0, 0, 75, 1, 0, 0, 5, 100, 0, 0, 80, 0, 0,
        0, 185, 0, 0, 0, 148, 1, 0, 0, 5, 44, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 3, 0, 0, 0, 32, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 64, 0, 0, 0, 0, 0, 0, 0, 148, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 2, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 216, 0, 0, 0, 0, 0, 0, 0, 168, 0, 0, 0,
        0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 24, 0, 0, 0, 0, 0, 0, 0, 17, 0,
        0, 0, 1, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 128, 1, 0, 0, 0, 0, 0, 0,
        96, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 33, 0, 0, 0, 1, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 224, 1, 0,
        0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 41, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 228, 1, 0, 0, 0, 0, 0, 0, 37, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 114, 0, 0, 0, 9, 0, 0, 0, 64, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 16, 2, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0,
        0, 8, 0, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0, 134, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 32, 2, 0, 0, 0, 0, 0, 0, 238, 3, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 139, 0, 0, 0, 1, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 16, 6, 0, 0, 0, 0, 0, 0, 144, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    ];
}
