[package]
name = "beeline"
version = "0.1.0"
edition = "2021"
description = "An experiment to explore the feasibility of composing valid BPF code snippets."

[lib]
name = "beeline"
path = "src/proxy.rs"

[[bin]]
name = "beeline"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.17", features = ["derive"] }
common = { path = "../common" }
env_logger = "0.11.5"
libbpf-rs = { git = "https://github.com/libbpf/libbpf-rs.git", features = [
    "vendored",
], branch = "master" }
libbpf-sys = "1.4.5"
libc = "0.2.155"
log = "0.4.22"
serde_yaml = "0.9.34"
as-bytes = "0.2.0"
serde = { version = "1.0.213", features = ["derive"] }
tokio = { version = "1.41.0", features = ["full"] }
httparse = "1.9.5"
sha2 = "0.10.8"

[build-dependencies]
libbpf-cargo = "0.24"

[dev-dependencies]
rand = "0.8.5"
