[package]
name = "baseline"
version = "0.1.0"
edition = "2021"
description = "An IPC accelerator à la Cilium"

[lib]
name = "baseline"
path = "src/proxy.rs"

[[bin]]
name = "baseline"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.86"
as-bytes = "0.2.0"
clap = { version = "4.5.17", features = ["derive"] }
common = { path = "../common" }
env_logger = "0.11.5"
libbpf-rs = { git = "https://github.com/libbpf/libbpf-rs.git", features = [
    "vendored",
], branch = "master" }
libbpf-sys = "1.4.5"
libc = "0.2.155"
log = "0.4.22"
tokio = { version = "1.41.0", features = ["full"] }

[build-dependencies]
libbpf-cargo = "0.24"
