[package]
name = "baseline"
version = "0.1.0"
edition = "2021"

[lib]
name = "baseline"
path = "src/proxy.rs"

[[bin]]
name = "baseline"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.93"
clap = { version = "4.5.21", features = ["derive"] }
env_logger = "0.11.5"
futures = "0.3.31"
hmac = "0.12.1"
httparse = "1.9.5"
jwt = "0.16.0"
log = "0.4.22"
sha2 = "0.10.8"
tokio = { version = "1.41.1", features = ["full", "io-util"] }

[dev-dependencies]
tests = { path = "../tests" }
