[package]
name = "proxy-ebpf"
version = "0.1.0"
edition = "2021"
description = "An experiment to explore the feasibility of composing valid BPF code snippets."

[lib]
name = "eproxy"
path = "src/proxy.rs"

[[bin]]
name = "proxy-ebpf"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.17", features = ["derive"] }
env_logger = "0.11.5"
libbpf-rs = { version = "0.24", features = ["vendored"] }
libbpf-sys = "1.4.5"
libc = "0.2.155"
log = "0.4.22"
common = { version = "0.1.0", path = "../common" }
serde_yaml = "0.9.34"
as-bytes = "0.2.0"
socket2 = "0.5.7"

[build-dependencies]
libbpf-cargo = "0.24"

[dev-dependencies]
rand = "0.8.5"
